Fix extractor error
Due to a bug extractor was giving:

   NoMethodError: undefined method `validate' for
                  Restapi::Validator::NumberValidator:Class